In [23]:
import pandas as pd
import requests
from io import StringIO

In [24]:
df_nger = pd.read_csv("NGER.ID0243.csv")

df_accredited = pd.read_csv("power-stations-and-projects-accredited.csv")
df_committed = pd.read_csv("power-stations-and-projects-committed.csv")
df_probable = pd.read_csv("power-stations-and-projects-probable.csv")

In [25]:
abs_url = "https://data.api.abs.gov.au/rest/data/ABS,ABS_REGIONAL_ASGS2021,/..AUS.A?startPeriod=2020&dimensionAtObservation=AllDimensions"

headers = {
    "Accept": "application/vnd.sdmx.data+csv;labels=both"
}

response = requests.get(abs_url, headers=headers, timeout=60)
response.raise_for_status()

df_abs = pd.read_csv(StringIO(response.text))

In [26]:
print("NGER shape:", df_nger.shape)
display(df_nger.head())

NGER shape: (775, 14)

,Reporting entity,Facility name,Type,State,Electricity production GJ,Electricity production MWh,Total scope 1 emissions t CO2 e,Total scope 2 emissions t CO2 e,Total emissions t CO2 e,Emission intensity t CO2 e MWh,Grid connected,Grid,Primary fuel,Important notes
0,ACCIONA ENERGY OCEANIA PTY LTD,Cathedral Rocks Wind Farm,F,SA,481948,133874,57,127.0,184,0.0,On,NEM,Wind,-
1,ACCIONA ENERGY OCEANIA PTY LTD,Gunning Wind Farm,F,NSW,491409,136502,50,218.0,268,0.0,On,NEM,Wind,-
2,ACCIONA ENERGY OCEANIA PTY LTD,Mortlake South Wind Farm,F,VIC,1019352,283153,202,1128.0,1330,0.0,On,NEM,Wind,-
3,ACCIONA ENERGY OCEANIA PTY LTD,Mt Gellibrand Wind Farm,F,VIC,1025451,284847,99,1273.0,1372,0.0,On,NEM,Wind,-
4,ACCIONA ENERGY OCEANIA PTY LTD,Waubra Wind Farm,F,VIC,1954964,543046,186,1114.0,1300,0.0,On,NEM,Wind,-

In [27]:
print("Accredited shape:", df_accredited.shape)
display(df_accredited.head())

Accredited shape: (36, 8)

,Accreditation code,Power station name,State,Postcode,Installed capacity (MW),Fuel Source (s),Accreditation start date,Approval date
0,SRPXQLO8,DONS FORT - SOLAR W SGU - QLD,QLD,4660,0.421,Solar,21/10/2025,6/01/2026
1,SRPYNSK0,Mintus Coles - Solar w SGU- NSW,NSW,2153,0.190,Solar,9/12/2025,6/01/2026
2,SRPXQLP1,Ventora - Acacia Ridge - Solar - QLD,QLD,4110,0.162,Solar,17/11/2025,6/01/2026
3,SRPYNSK3,Bayside Aged Care - Solar - Morisset - NSW,NSW,2264,0.140,Solar,16/12/2025,8/01/2026
4,SRPVWAQ0,Matrix Composites and Engineering Pty Ltd - So...,WA,6166,0.850,Solar,17/12/2025,8/01/2026

In [28]:
print("Committed shape:", df_committed.shape)
display(df_committed.head())

Committed shape: (36, 5)

,Project Name,State,MW Capacity,Fuel Source,Committed Date (Month/Year)
0,East Rockingham Resource Recovery Facility,WA,29.0,Biomass,Dec-2019
1,Mangalore Renewable Energy Project,VIC,5.0,Solar,Sep-2021
2,Orange Community Renewable Energy Park,NSW,5.0,Solar,Jul-2022
3,Moorebank Logistics Park,NSW,60.0,Solar,Sep-2022
4,Kidston Pumped Hydro Storage Project,QLD,250.0,Hydro,Jul-2023

In [29]:
print("Probable shape:", df_probable.shape)
display(df_probable.head())

Probable shape: (59, 4)

              Probable Projects State  MW Capacity Fuel Source
0        Barnawartha Solar Farm    VIC      64.000       Solar
1             Barwon solar farm    VIC     250.000       Solar
2            Bell Bay Wind Farm    TAS     224.000        Wind
3  Bendemeer Energy Hub - Solar    NSW     252.000       Solar
4      Binningup Solar Facility     WA      75.000       Solar

In [30]:
print("ABS shape:", df_abs.shape)
display(df_abs.head())

ABS shape: (1693, 11)

,DATAFLOW,MEASURE: Data Item,REGIONTYPE: Region Type,ASGS_2021: Region,FREQUENCY: Frequency,TIME_PERIOD: Time Period,OBS_VALUE,UNIT_MEASURE: Unit of Measure,UNIT_MULT: Unit of Multiplier,OBS_STATUS: Observation Status,OBS_COMMENT: Observation Comment
0,ABS:ABS_REGIONAL_ASGS2021(1.5.0),VEHIC_2: Households with no motor vehicles (no.),AUS: Australia,AUS: Australia,A: Annual,2021,673969.0,NUM: Number,NaN,NaN,NaN
1,ABS:ABS_REGIONAL_ASGS2021(1.5.0),ING_TTYPE1: Aboriginal and Torres Strait Islan...,AUS: Australia,AUS: Australia,A: Annual,2021,280385.0,PSNS: Persons,NaN,NaN,NaN
2,ABS:ABS_REGIONAL_ASGS2021(1.5.0),ERP_P_38: Estimated resident population:Person...,AUS: Australia,AUS: Australia,A: Annual,2020,2.0,PCT: Percent,NaN,NaN,NaN
3,ABS:ABS_REGIONAL_ASGS2021(1.5.0),ERP_P_38: Estimated resident population:Person...,AUS: Australia,AUS: Australia,A: Annual,2021,2.1,PCT: Percent,NaN,NaN,NaN
4,ABS:ABS_REGIONAL_ASGS2021(1.5.0),ERP_P_38: Estimated resident population:Person...,AUS: Australia,AUS: Australia,A: Annual,2022,2.1,PCT: Percent,NaN,NaN,NaN

In [31]:
print("NGER columns:")
display(df_nger.columns)

print("Accredited columns:")
display(df_accredited.columns)

print("Committed columns:")
display(df_committed.columns)

print("Probable columns:")
display(df_probable.columns)

print("ABS columns:")
display(df_abs.columns)

NGER columns:

Index(['Reporting entity', 'Facility name', 'Type', 'State',
       'Electricity production GJ', 'Electricity production MWh',
       'Total scope 1 emissions t CO2 e', 'Total scope 2 emissions t CO2 e',
       'Total emissions t CO2 e', 'Emission intensity t CO2 e MWh',
       'Grid connected', 'Grid', 'Primary fuel', 'Important notes'],
      dtype='object')

Accredited columns:

Index(['Accreditation code', 'Power station name', 'State', 'Postcode',
       'Installed capacity (MW)', 'Fuel Source (s)',
       'Accreditation start date', 'Approval date'],
      dtype='object')

Committed columns:

Index(['Project Name', 'State ', 'MW Capacity', 'Fuel Source',
       'Committed Date (Month/Year)'],
      dtype='object')

Probable columns:

Index(['Probable Projects', 'State ', 'MW Capacity', 'Fuel Source'], dtype='object')

ABS columns:

Index(['DATAFLOW', 'MEASURE: Data Item', 'REGIONTYPE: Region Type',
       'ASGS_2021: Region', 'FREQUENCY: Frequency', 'TIME_PERIOD: Time Period',
       'OBS_VALUE', 'UNIT_MEASURE: Unit of Measure',
       'UNIT_MULT: Unit of Multiplier', 'OBS_STATUS: Observation Status',
       'OBS_COMMENT: Observation Comment'],
      dtype='object')

## merge power-stations-and-projects data

In [32]:
# remove extra spaces in column names
df_accredited.columns = df_accredited.columns.str.strip()
df_committed.columns = df_committed.columns.str.strip()
df_probable.columns = df_probable.columns.str.strip()

# -------------------------
# accredited
# -------------------------
df_accredited_full = df_accredited.rename(columns={
    "Power station name": "project_name",
    "State": "state",
    "Installed capacity (MW)": "capacity_mw",
    "Fuel Source (s)": "fuel_source",
    "Accreditation code": "accreditation_code",
    "Postcode": "postcode",
    "Accreditation start date": "accreditation_start_date",
    "Approval date": "approval_date"
}).copy()

df_accredited_full["committed_date"] = pd.NA
df_accredited_full["project_status"] = "accredited"

# -------------------------
# committed
# -------------------------
df_committed_full = df_committed.rename(columns={
    "Project Name": "project_name",
    "State": "state",
    "MW Capacity": "capacity_mw",
    "Fuel Source": "fuel_source",
    "Committed Date (Month/Year)": "committed_date"
}).copy()

df_committed_full["accreditation_code"] = pd.NA
df_committed_full["postcode"] = pd.NA
df_committed_full["accreditation_start_date"] = pd.NA
df_committed_full["approval_date"] = pd.NA
df_committed_full["project_status"] = "committed"

# -------------------------
# probable
# -------------------------
df_probable["MW Capacity"] = (
    df_probable["MW Capacity"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

df_probable_full = df_probable.rename(columns={
    "Probable Projects": "project_name",
    "State": "state",
    "MW Capacity": "capacity_mw",
    "Fuel Source": "fuel_source"
}).copy()

df_probable_full["capacity_mw"] = pd.to_numeric(df_probable_full["capacity_mw"], errors="coerce")
df_probable_full["accreditation_code"] = pd.NA
df_probable_full["postcode"] = pd.NA
df_probable_full["accreditation_start_date"] = pd.NA
df_probable_full["approval_date"] = pd.NA
df_probable_full["committed_date"] = pd.NA
df_probable_full["project_status"] = "probable"

# -------------------------
# unify column order
# -------------------------
cer_columns = [
    "project_name",
    "state",
    "capacity_mw",
    "fuel_source",
    "project_status",
    "accreditation_code",
    "postcode",
    "accreditation_start_date",
    "approval_date",
    "committed_date"
]

df_accredited_full = df_accredited_full.reindex(columns=cer_columns)
df_committed_full = df_committed_full.reindex(columns=cer_columns)
df_probable_full = df_probable_full.reindex(columns=cer_columns)

# -------------------------
# combine all CER tables
# -------------------------
df_cer = pd.concat(
    [df_accredited_full, df_committed_full, df_probable_full],
    ignore_index=True
)

# optional checks
print(df_cer.head())
print(df_cer.info())
print(df_cer.isna().sum())

                                        project_name state  capacity_mw  \
0                      DONS FORT - SOLAR W SGU - QLD   QLD        0.421
1                    Mintus Coles - Solar w SGU- NSW   NSW        0.190
2               Ventora - Acacia Ridge - Solar - QLD   QLD        0.162
3         Bayside Aged Care - Solar - Morisset - NSW   NSW        0.140
4  Matrix Composites and Engineering Pty Ltd - So...    WA        0.850

  fuel_source project_status accreditation_code postcode  \
0       Solar     accredited           SRPXQLO8     4660
1       Solar     accredited           SRPYNSK0     2153
2       Solar     accredited           SRPXQLP1     4110
3       Solar     accredited           SRPYNSK3     2264
4       Solar     accredited           SRPVWAQ0     6166

  accreditation_start_date approval_date committed_date
0               21/10/2025     6/01/2026            NaN
1                9/12/2025     6/01/2026            NaN
2               17/11/2025     6/01/2026            NaN
3               16/12/2025     8/01/2026            NaN
4               17/12/2025     8/01/2026            NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   project_name              131 non-null    object
 1   state                     131 non-null    object
 2   capacity_mw               131 non-null    float64
 3   fuel_source               131 non-null    object
 4   project_status            131 non-null    object
 5   accreditation_code        36 non-null     object
 6   postcode                  36 non-null     object
 7   accreditation_start_date  36 non-null     object
 8   approval_date             36 non-null     object
 9   committed_date            36 non-null     object
dtypes: float64(1), object(9)
memory usage: 10.4+ KB
None
project_name                 0
state                        0
capacity_mw                  0
fuel_source                  0
project_status               0
accreditation_code          95
postcode                    95
accreditation_start_date    95
approval_date               95
committed_date              95
dtype: int64